[[permission]]
identifier = "allow-save"
description = "Enables the saving of the processed data"
commands.allow = ["save"]

[[permission]]
identifier = "allow-load"
description = "Enables the loading of saved data"
commands.allow = ["load"]

[[permission]]
identifier = "default"
description = "Default permissions for the save system"
permissions = ["allow-save", "allow-load"]
