[env]
MYSQL_CONNECTION_STRING = 'mysql://root:password@localhost:3306/po_tracker'

# Secrets
JWT_SECRET = 'development-jwt-secret'
HASH_SALT = 'development-hash-salt'

# File uploads
PO_UPLOAD_DIR = './uploads/po_files'

# Email configuration
SMTP_HOST = ""
SMTP_USERNAME = ""
SMTP_PASSWORD = ""

[target.x86_64-pc-windows-msvc]
linker = "lld-link"